feat: #4 GameList에 사용될 커스텀 UICollectionViewCell 정의
JustCommitIt/GameScope pull request #19
Opened 2023-07-01 08:28 UTC by sloDevz

GameDTO로부터 convert 된 Game 모델을 사용해서 Cell을 설정하는 로직으로 만들었습니다~~😄

2023-07-01 09:36 UTC, ohdair requested changes
addSubView가 존재하지 않아서 에러가 발생하는 거 같아요

2023-07-01 09:36 UTC, ohdair commented on GameScope/GameScope/View/gameListCollectionViewCell.swift
> +            make.centerX.equalToSuperview()
`leading`으로 설정했는데 `centerX`으로 layout설정 하게 되면 중첩된 의미로 사용될 거 같아요

2023-07-01 09:36 UTC, ohdair commented on GameScope/GameScope/View/gameListCollectionViewCell.swift
> +        gameDescribsionLabel.text = game.shortDescription
1. DTO를 넘기기보다는 convert된 값을 넣어주는 게 더 명확할 거 같아요
2. thumbnail의 오타가 있어요
3. UIImage를 넘겨준다는 의미는 모든 데이터에 해당되는 이미지를 미리 다운받는 로직인가요?

2023-07-01 14:58 UTC, sloDevz commented on GameScope/GameScope/View/gameListCollectionViewCell.swift
> +        gameDescribsionLabel.text = game.shortDescription
넵! 리스트를 출력할 때 모든 게임의 썸네일 이미지가 필요하기 때문에 어쩔 수 없이 모두 요청해야 할 것 같아요

2023-07-01 14:59 UTC, sloDevz commented on GameScope/GameScope/View/gameListCollectionViewCell.swift
> +            make.centerX.equalToSuperview()
X와 Y를 착각했었네요 😅

2023-07-01 23:35 UTC, ohdair commented
<img width="300px" src="https://github.com/JustCommitIt/GameScope/assets/79438622/66095df0-8a77-4cfb-b063-64d4dd7cb3a4">

해당 Cell을 보게되면 위 사진과 같은 레이아웃이 문제가 되는 거 같아요.
Cell 레이아웃에 대해서 높이는 설정으로 맞출 수 있겠지만, description과 title이 겹치는 문제도 있는 거 같아요.

2023-07-01 23:36 UTC, ohdair requested changes

2023-07-01 23:36 UTC, ohdair commented on GameScope/GameScope/View/gameListCollectionViewCell.swift
> +            make.top.equalTo(gameTitleLabel)
`gameThumbnailImageView`의 trailing과 같아야 될 거 같아요

2023-07-02 08:20 UTC, ohdair approved these changes
![스크린샷 2023-07-02 오후 5 19 44](https://github.com/JustCommitIt/GameScope/assets/79438622/ae4cd12a-c138-42c7-a5bf-dba11829bdcc)

Controller가 참조가 제대로 안되어 있는 거 같아요. 붉은 글씨로 씌여있어요

2023-07-02 08:20 UTC, ohdair commented on GameScope/GameScope/View/gameListCollectionViewCell.swift
> +        }
중간에 개행이 들어가 있는데, 통일성있게 나타내면 좋을 거 같아요

2023-07-02 08:32 UTC, merged