Logan/#20/create collection view list for game list
JustCommitIt/GameScope pull request #22
Opened 2023-07-08 07:15 UTC by sloDevz

2023-07-12 07:04 UTC, ohdair requested changes
수고하셨습니다.
코드 스타일에 대한 것은 오프라인 회의를 통해서 결정해봐요

2023-07-13 03:16 UTC, ohdair requested changes

2023-07-13 03:16 UTC, ohdair commented on GameScope/GameScope/View/GameListCollectionViewCell.swift
> +    func updateThumbnail(with  thumbnail: UIImage?) {
띄어쓰기가 2번 들어갔어요

2023-07-13 03:16 UTC, ohdair commented on GameScope/GameScope/Controllers/GameListCollectionViewController.swift
> +            }
`GameListCollectionViewController`에서 Cell을 구성하는 부분에서
`Task` 하는 부분이 Cell 내부에서 처리하는 게 더 보기 좋을 거 같은데, 외부에 노출(?)하신 이유가 있을까요?

2023-07-13 07:10 UTC, ohdair commented on GameScope/GameScope/Controllers/GameListCollectionViewController.swift
> +            }
asdasdasd

2023-07-13 07:16 UTC, sloDevz commented
가다라다

2023-07-13 07:22 UTC, ohdair reviewed
수고하셨습니다 👍

2023-07-13 07:23 UTC, ohdair approved these changes
수고하셨습니다 :+1:

2023-07-13 07:24 UTC, merged